### ISSUE TITLE
use const instead of static!

### ISSUE THREAD

**Issue by sn99** [SubconsciousCompute/naughtyfy#1]
https://github.com/tanveerraza789/naughtyfy/blob/8e88d1b99a5a139e51622e5298b1922e02242093/src/low_layer.rs#L11

https://doc.rust-lang.org/std/mem/fn.size_of.html

**Comment by tanveerraza789** [comment]
`FAN_EVENT_METADATA_LEN` is runtime-computed and platform dependent constant hence we cannot use `const` here which is a compile time constant.

If we are 100% sure about the platform we will be running this on, then we can make it const.

**Comment by radiohertz** [comment]
why cant we use a const here again? `std::mem::size_of::<fanotify_event_metadata>()` will never change between platforms.

**Comment by tanveerraza789** [comment]
Yes, you're right. The mem size will be the same. I will make it const.

**Comment by tanveerraza789** [comment]
Fixed in https://github.com/SubconsciousCompute/naughtyfy/pull/5
